### ISSUE TITLE
The command works weirdly...

### ISSUE THREAD

**Issue by xbenas** [jb42300/Resource-Pack-Downloader#2]
The command works strange...
I have set it as **/rp** in config.
If I make a player do the command like **/rp** then it says no such command exists, but when player writes **/rp**, then it works.
Also if I make an alias in *commands.yml* for **/rp** then it doesn't work.
Please check on this issue.

**Comment by jb42300** [comment]
Will work on this right now. Thank you for the report!

**Comment by jb42300** [comment]
Edit note: Witch version are you using?

**Comment by jb42300** [comment]
I think i have fixed the problem. Use the 2.0 update for better understanding of the message.
Also please tell me if this is fixed so i can lable this ticket as fixed! Thank you again!
