### ISSUE TITLE
PerWorldResourcepack

### ISSUE THREAD

**Issue by PinoyLifeCraft** [jb42300/Resource-Pack-Downloader#5]
Hello there @jb42300 ,

This is what I set on my config
General:
  Resourcepack: **_Private xD_**
  Is-Global: false
  Command:
    Command: rp
    Is-Case-Sensitive: false
  Events:
    Join:
      Use-Bypass-Permission: false
      Bypass-Permission: RPD.bypassjoin
      Send-On-Join: true
Commands:
  Accepted-Pack:
    Enabled: true
    Command: tm msg %PLAYER% &f<nl>&2&lDownloading...
  Declined-Pack:
    Enabled: false
    Command: kick %PLAYER% &4&lWarning &rPlease Enable Server Resource Packs to see &3&lEmoji &rInstallation Guide &chttp://www.pinoylifecraft.com/installation/ &bxD
  Downloaded-Pack:
    Enabled: true
    Command: tm msg %PLAYER% &f<nl>&f䳣䳜䳡&e䳢䳬 &1䳟䳜䳙䳘&4䳣䳔䳖䳞
  Failed-Download-Pack:
    Enabled: true
    Command: tm msg %PLAYER% &6&lDownload Failure<nl>&cPlease try again! Do &7/rp
Messages:
  Enable-Accepted-Downloaded-Message: false
  Enable-Declined-Downloaded-Message: true
  Enable-Downloaded-Message: false
  Enable-Failed-Downloaded-Message: false
Worlds:
  soldiercraft:
    Enabled: true
    Resourcepack-URL: **_Private xD_**
  faction:
    Enabled: false
    Resourcepack-URL: some.url.here
  faction_nether:
    Enabled: false
    Resourcepack-URL: some.url.here
  faction_the_end:
    Enabled: false
    Resourcepack-URL: some.url.here
So I set the world name "soldiercraft" but when I join **and** when I am in the world "soldiercraft" the pack that send to me was the General Pack 🙁 so **I have to go to the other world and back to soldiercraft in order to load the soldiercraft RP .** can you **_Fix_** it pls?

**Comment by jb42300** [comment]
Already handled it for you in the discussion tab on spigot! Thank you!
